.TH OPENTELEMETRY\-BOOTSTRAP "1" "August 2021" "" "User Commands"
.SH NAME
.B opentelemetry\-bootstrap
\(en detects installed libraries and automatically installs the relevant
instrumentation packages for them
.SH SYNOPSIS
.B opentelemetry\-bootstrap
.RB [ \-h ]
.RB [ \-a
.RB { install , requirements }]
.SH OPTIONS
.TP
.B \-h\fR,\ \fB\-\-help
show a help message and exit
.TP
.B \-a\fR\ {\fBinstall\fR,\fBrequirements\fR},\ \fB\-\-action\fR\ {\fBinstall\fR,\fBrequirements\fR}
.RS +7n
.TP
.B install
uses
.BR pip (1)
to install the new requirements using to the currently active site-package.
.TP
.B requirements
prints out the new requirements to
.IR stdout .
Action can be piped and appended to a
.B requirements.txt
file.
.RE
.SH "SEE\ ALSO"
.BR opentelemetry\-instrument (1)
